#pragma once
#ifndef __GAME_MACRO_H__
#define __GAME_MACRO_H__

#define MAX_TEXAS_HANDCARD_NUM		 (2)
#define MAX_TEXAS_BETROUND_NUM		 (4)
#define MAX_TEXAS_CENTERCARD_NUM	 (5)
#define MAX_TEXAS_DEALERCARD_NUM	 (9)
#define MAX_TEXAS_HISTORYBOARD_NUM	 (10)
#define MAX_TEXAS_GAMESTART_INTERVAL (21)
#define MAX_TEXAS_BETBROADCAST_NUM	 (30)
#define MAX_TEXAS_GAMEFULLCARD_NUM	 (52)

#endif //__GAME_MACRO_H__