#ifndef __CS_PROTOCOL_H__
#define __CS_PROTOCOL_H__

//CLIENT - GATE - GS
//Protocol ID:[10001-20000](Base :10000)
enum ECS_PROTOCOL
{
	ECS_BEGIN = 10000,
	////////////////////////////////////////////////////////////////////////////////////////////////
	//PING HEARTBEAT
	ECS_PING_C2GT_HEARTBEAT_REQ = ECS_BEGIN + 1,
	ECS_PING_GT2C_HEARTBEAT_RES = ECS_BEGIN + 2,

	//LOGIN
	ECS_LOGIN_C2GT2S_USERLOGIN_REQ = ECS_BEGIN + 3,
	ECS_LOGIN_S2GT2C_USERLOGIN_RES = ECS_BEGIN + 4,

	////////////////////////////////////////////////////////////////////////////////////////////////
	//ROLE
	ECS_ROLE_S2GT2C_ROLEINFO_SYNC = ECS_BEGIN + 5,

	////////////////////////////////////////////////////////////////////////////////////////////////
	//HALLROOM
	ECS_HALLROOM_C2GT2S_ENTERROOM_REQ = ECS_BEGIN + 6,
	ECS_HALLROOM_S2GT2C_ENTERROOM_RES = ECS_BEGIN + 7,

	ECS_HALLROOM_C2GT2S_LEAVEROOM_REQ = ECS_BEGIN + 8,
	ECS_HALLROOM_S2GT2C_LEAVEROOM_RES = ECS_BEGIN + 9,

	ECS_HALLROOM_C2GT2S_SITDOWN_REQ = ECS_BEGIN + 10,
	ECS_HALLROOM_S2GT2C_SITDOWN_RES = ECS_BEGIN + 11,

	ECS_HALLROOM_C2GT2S_STANDUP_REQ = ECS_BEGIN + 12,
	ECS_HALLROOM_S2GT2C_STANDUP_RES = ECS_BEGIN + 13,

	////////////////////////////////////////////////////////////////////////////////////////////////
	//TEXASGAME

	//GIRLCHANGE
	ECS_TEXASGAME_S2GT2C_GIRLCHANGE_SYNC = ECS_BEGIN + 14,

	//START GAME
	ECS_TEXASGAME_S2GT2C_STARTGAME_SYNC = ECS_BEGIN + 15,

	//DEALCARD
	ECS_TEXASGAME_S2GT2C_DEALCARD_SYNC = ECS_BEGIN + 16,

	//DEALCARD
	ECS_TEXASGAME_S2GT2C_NOTICEBET_SYNC = ECS_BEGIN + 17,

	// BET
	ECS_TEXASGAME_C2GT2S_BET_REQ = ECS_BEGIN + 18,
	ECS_TEXASGAME_S2GT2C_BET_RES = ECS_BEGIN + 19,

	//FOLD
	ECS_TEXASGAME_C2GT2S_FOLD_REQ = ECS_BEGIN + 20,
	ECS_TEXASGAME_S2GT2C_FOLD_RES = ECS_BEGIN + 21,

	//SETTLEMENT
	ECS_TEXASGAME_S2GT2C_GAMESETTLEMENT_SYNC = ECS_BEGIN + 22,

	//GIRLCANCEl
	ECS_TEXASGAME_S2GT2C_GIRLCANCEL_SYNC = ECS_BEGIN + 23,

	//BET BROADCAS
	ECS_BROADCAST_S2GT2C_BET_SYNC = ECS_BEGIN + 24,

	//BRAND BROADCAST
	ECS_BROADCAST_S2GT2C_BRAND_SYNC = ECS_BEGIN + 25,

	//ONLINE BROADCAST
	ECS_BROADCAST_S2GT2C_ONLINE_SYNC = ECS_BEGIN + 26,

	//Extra Sync

	//CARDLIST
	ECS_TEXASGAME_S2GT2C_CARDLIST_SYNC = ECS_BEGIN + 27,

	//REWARDPOOL
	ECS_TEXASGAME_S2GT2C_REWARDPOOL_SYNC = ECS_BEGIN + 28,

	//READYLEAVE
	ECS_TEXASGAME_C2GT2S_READYLEAVEROOM_REQ = ECS_BEGIN + 29,

	//READYLEAVE
	ECS_TEXASGAME_S2GT2C_READYLEAVEROOM_RES = ECS_BEGIN + 30,

	//HISTORYBOARD
	ECS_TEXASGAME_S2GT2C_HISTORYBOARD_SYNC = ECS_BEGIN + 31,

	////////////////////////////////////////////////////////////////////////////////////////////////
	ECS_ERROR_S2GT2C_ERRORCODE_SYNC = ECS_BEGIN + 9999,

	////////////////////////////////////////////////////////////////////////////////////////////////
	ECS_END = 20000,
};

#endif//__CS_PROTOCOL_H__
