#ifndef __SDL_PROTOCOL_H__
#define __SDL_PROTOCOL_H__

//Protocol ID:50001-60000-1(Base :50000)
enum ESDL_PROTOCOL
{
	ESDL_BEGIN = 50000,
	////////////////////////////////////////////////////////////////////////////////////////////////

	//PING HEARTBEAT
	ESDL_PING_S2DL_HEARTBEAT_REQ = ESDL_BEGIN + 1,
	ESDL_PING_DL2S_HEARTBEAT_RES = ESDL_BEGIN + 2,

	//BET
	ESDL_BET_S2DL_SAVE_BET_REQ = ESDL_BEGIN + 3,
	ESDL_BET_DL2S_SAVE_BET_RES = ESDL_BEGIN + 4,

	//LOGIN
	ESDL_LOGIN_S2DL_SAVE_LOGIN_REQ = ESDL_BEGIN + 5,
	ESDL_LOGIN_DL2S_SAVE_LOGIN_RES = ESDL_BEGIN + 6,

	//LOGOUT
	ESDL_LOGOUT_S2DL_SAVE_LOGOUT_REQ = ESDL_BEGIN + 7,
	ESDL_LOGOUT_DL2S_SAVE_LOGOUT_RES = ESDL_BEGIN + 8,

	//ONLINE
	ESDL_ONLINE_S2DL_SAVE_ONLINE_REQ = ESDL_BEGIN + 9,
	ESDL_ONLINE_DL2S_SAVE_ONLINE_RES = ESDL_BEGIN + 10,

	//PVGGIFT
	ESDL_PVGGIFT_S2DL_SAVE_PVG_GIFT_REQ = ESDL_BEGIN + 11,
	ESDL_PVGGIFT_DL2S_SAVE_PVG_GIFT_RES = ESDL_BEGIN + 12,

	//PVPGIFT
	ESDL_PVPGIFT_S2DL_SAVE_PVP_GIFT_REQ = ESDL_BEGIN + 13,
	ESDL_PVPGIFT_DL2S_SAVE_PVP_GIFT_RES = ESDL_BEGIN + 14,

	//ROOM
	ESDL_ROOM_S2DL_SAVE_ROOM_REQ = ESDL_BEGIN + 15,
	ESDL_ROOM_DL2S_SAVE_ROOM_RES = ESDL_BEGIN + 16,

	//TRACE
	ESDL_TRACE_S2DL_SAVE_TRACE_REQ = ESDL_BEGIN + 17,
	ESDL_TRACE_DL2S_SAVE_TRACE_RES = ESDL_BEGIN + 18,

	//GM
	ESDL_GM_S2DL_SAVE_GM_REQ = ESDL_BEGIN + 19,
	ESDL_GM_DL2S_SAVE_GM_RES = ESDL_BEGIN + 20,

	ESDL_TEST_S2DL_TEST_REQ = ESDL_BEGIN + 21,
	ESDL_TEST_DL2S_TEST_RES = ESDL_BEGIN + 22,

	////////////////////////////////////////////////////////////////////////////////////////////////
	ESDL_END = 60000,
};

#endif//__SDL_PROTOCOL_H__